sudo: false # force container-based infrastructure
language: node_js
node_js:
  - "4.3"
install:
  - npm install -g elm@0.16.0
before_script:
  - bash tests/set-up-tests.sh
script:
  - node tests/test.js
